/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Jan 18 17:23:59 EST 2006 by MyEclipse Hibernate Tool.
 */
package gov.nih.nlm.semmed.model;

import java.io.Serializable;

/**
 * A class that represents a row in the SENTENCE table. 
 * You can customize the behavior of this class by editing the class, {@link Sentence()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSentence 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long sentenceId;

    /** The value of the sentencePredicationSet one-to-many association. */
    private java.util.Set sentencePredicationSet;

    /** The value of the simple pmid property. */
    private java.lang.String pmid;

    /** The value of the simple type property. */
    private java.lang.String type;

    /** The value of the simple number property. */
    private java.lang.Integer number;

    /** The value of the simple sentence property. */
    private java.lang.String sentence;

    /**
     * Simple constructor of AbstractSentence instances.
     */
    public AbstractSentence()
    {
    }

    /**
     * Constructor of AbstractSentence instances given a simple primary key.
     * @param sentenceId
     */
    public AbstractSentence(java.lang.Long sentenceId)
    {
        this.setSentenceId(sentenceId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Long getSentenceId()
    {
        return sentenceId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param sentenceId
     */
    public void setSentenceId(java.lang.Long sentenceId)
    {
        this.hashValue = 0;
        this.sentenceId = sentenceId;
    }

    /**
     * Return the value of the PMID column.
     * @return java.lang.String
     */
    public java.lang.String getPmid()
    {
        return this.pmid;
    }

    /**
     * Set the value of the PMID column.
     * @param pmid
     */
    public void setPmid(java.lang.String pmid)
    {
        this.pmid = pmid;
    }

    /**
     * Return the value of the TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getType()
    {
        return this.type;
    }

    /**
     * Set the value of the TYPE column.
     * @param type
     */
    public void setType(java.lang.String type)
    {
        this.type = type;
    }

    /**
     * Return the value of the NUMBER column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getNumber()
    {
        return this.number;
    }

    /**
     * Set the value of the NUMBER column.
     * @param number
     */
    public void setNumber(java.lang.Integer number)
    {
        this.number = number;
    }

    /**
     * Return the value of the SENTENCE column.
     * @return java.lang.String
     */
    public java.lang.String getSentence()
    {
        return this.sentence;
    }

    /**
     * Set the value of the SENTENCE column.
     * @param sentence
     */
    public void setSentence(java.lang.String sentence)
    {
        this.sentence = sentence;
    }

    /**
     * Return the value of the SENTENCE_ID collection.
     * @return SentencePredication
     */
    public java.util.Set getSentencePredicationSet()
    {
        return this.sentencePredicationSet;
    }

    /**
     * Set the value of the SENTENCE_ID collection.
     * @param sentencePredicationSet
     */
    public void setSentencePredicationSet(java.util.Set sentencePredicationSet)
    {
        this.sentencePredicationSet = sentencePredicationSet;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Sentence))
            return false;
        Sentence that = (Sentence) rhs;
        if (this.getSentenceId() == null || that.getSentenceId() == null)
            return false;
        return (this.getSentenceId().equals(that.getSentenceId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int sentenceIdValue = this.getSentenceId() == null ? 0 : this.getSentenceId().hashCode();
            result = result * 37 + sentenceIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
