/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Mar 27 11:16:11 EST 2006 by MyEclipse Hibernate Tool.
 */
package gov.nih.nlm.semmed.model;

import java.io.Serializable;

/**
 * A class that represents a row in the SENTENCE_PREDICATION table. 
 * You can customize the behavior of this class by editing the class, {@link SentencePredication()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSentencePredication 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long sentencePredicationId;

    /** The value of the sentence association. */
    private Sentence sentence;

    /** The value of the predication association. */
    private Predication predication;

    /** The value of the simple predicationNumber property. */
    private java.lang.Integer predicationNumber;

    /** The value of the simple subjectText property. */
    private java.lang.String subjectText;

    /** The value of the simple subjectDist property. */
    private java.lang.Integer subjectDist;

    /** The value of the simple subjectMaxdist property. */
    private java.lang.Integer subjectMaxdist;

    /** The value of the simple subjectStartIndex property. */
    private java.lang.Integer subjectStartIndex;

    /** The value of the simple subjectEndIndex property. */
    private java.lang.Integer subjectEndIndex;

    /** The value of the simple subjectScore property. */
    private java.lang.Integer subjectScore;

    /** The value of the simple indicatorType property. */
    private java.lang.String indicatorType;

    /** The value of the simple predicateStartIndex property. */
    private java.lang.Integer predicateStartIndex;

    /** The value of the simple predicateEndIndex property. */
    private java.lang.Integer predicateEndIndex;

    /** The value of the simple objectText property. */
    private java.lang.String objectText;

    /** The value of the simple objectDist property. */
    private java.lang.Integer objectDist;

    /** The value of the simple objectMaxdist property. */
    private java.lang.Integer objectMaxdist;

    /** The value of the simple objectStartIndex property. */
    private java.lang.Integer objectStartIndex;

    /** The value of the simple objectEndIndex property. */
    private java.lang.Integer objectEndIndex;

    /** The value of the simple objectScore property. */
    private java.lang.Integer objectScore;

    /**
     * Simple constructor of AbstractSentencePredication instances.
     */
    public AbstractSentencePredication()
    {
    }

    /**
     * Constructor of AbstractSentencePredication instances given a simple primary key.
     * @param sentencePredicationId
     */
    public AbstractSentencePredication(java.lang.Long sentencePredicationId)
    {
        this.setSentencePredicationId(sentencePredicationId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getSentencePredicationId()
    {
        return sentencePredicationId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param sentencePredicationId
     */
    public void setSentencePredicationId(java.lang.Long sentencePredicationId)
    {
        this.hashValue = 0;
        this.sentencePredicationId = sentencePredicationId;
    }

    /**
     * Return the value of the SENTENCE_ID column.
     * @return Sentence
     */
    public Sentence getSentence()
    {
        return this.sentence;
    }

    /**
     * Set the value of the SENTENCE_ID column.
     * @param sentence
     */
    public void setSentence(Sentence sentence)
    {
        this.sentence = sentence;
    }

    /**
     * Return the value of the PREDICATION_ID column.
     * @return Predication
     */
    public Predication getPredication()
    {
        return this.predication;
    }

    /**
     * Set the value of the PREDICATION_ID column.
     * @param predication
     */
    public void setPredication(Predication predication)
    {
        this.predication = predication;
    }

    /**
     * Return the value of the PREDICATION_NUMBER column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getPredicationNumber()
    {
        return this.predicationNumber;
    }

    /**
     * Set the value of the PREDICATION_NUMBER column.
     * @param predicationNumber
     */
    public void setPredicationNumber(java.lang.Integer predicationNumber)
    {
        this.predicationNumber = predicationNumber;
    }

    /**
     * Return the value of the SUBJECT_TEXT column.
     * @return java.lang.String
     */
    public java.lang.String getSubjectText()
    {
        return this.subjectText;
    }

    /**
     * Set the value of the SUBJECT_TEXT column.
     * @param subjectText
     */
    public void setSubjectText(java.lang.String subjectText)
    {
        this.subjectText = subjectText;
    }

    /**
     * Return the value of the SUBJECT_DIST column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSubjectDist()
    {
        return this.subjectDist;
    }

    /**
     * Set the value of the SUBJECT_DIST column.
     * @param subjectDist
     */
    public void setSubjectDist(java.lang.Integer subjectDist)
    {
        this.subjectDist = subjectDist;
    }

    /**
     * Return the value of the SUBJECT_MAXDIST column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSubjectMaxdist()
    {
        return this.subjectMaxdist;
    }

    /**
     * Set the value of the SUBJECT_MAXDIST column.
     * @param subjectMaxdist
     */
    public void setSubjectMaxdist(java.lang.Integer subjectMaxdist)
    {
        this.subjectMaxdist = subjectMaxdist;
    }

    /**
     * Return the value of the SUBJECT_START_INDEX column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSubjectStartIndex()
    {
        return this.subjectStartIndex;
    }

    /**
     * Set the value of the SUBJECT_START_INDEX column.
     * @param subjectStartIndex
     */
    public void setSubjectStartIndex(java.lang.Integer subjectStartIndex)
    {
        this.subjectStartIndex = subjectStartIndex;
    }

    /**
     * Return the value of the SUBJECT_END_INDEX column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSubjectEndIndex()
    {
        return this.subjectEndIndex;
    }

    /**
     * Set the value of the SUBJECT_END_INDEX column.
     * @param subjectEndIndex
     */
    public void setSubjectEndIndex(java.lang.Integer subjectEndIndex)
    {
        this.subjectEndIndex = subjectEndIndex;
    }

    /**
     * Return the value of the SUBJECT_SCORE column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getSubjectScore()
    {
        return this.subjectScore;
    }

    /**
     * Set the value of the SUBJECT_SCORE column.
     * @param subjectScore
     */
    public void setSubjectScore(java.lang.Integer subjectScore)
    {
        this.subjectScore = subjectScore;
    }

    /**
     * Return the value of the INDICATOR_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getIndicatorType()
    {
        return this.indicatorType;
    }

    /**
     * Set the value of the INDICATOR_TYPE column.
     * @param indicatorType
     */
    public void setIndicatorType(java.lang.String indicatorType)
    {
        this.indicatorType = indicatorType;
    }

    /**
     * Return the value of the PREDICATE_START_INDEX column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getPredicateStartIndex()
    {
        return this.predicateStartIndex;
    }

    /**
     * Set the value of the PREDICATE_START_INDEX column.
     * @param predicateStartIndex
     */
    public void setPredicateStartIndex(java.lang.Integer predicateStartIndex)
    {
        this.predicateStartIndex = predicateStartIndex;
    }

    /**
     * Return the value of the PREDICATE_END_INDEX column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getPredicateEndIndex()
    {
        return this.predicateEndIndex;
    }

    /**
     * Set the value of the PREDICATE_END_INDEX column.
     * @param predicateEndIndex
     */
    public void setPredicateEndIndex(java.lang.Integer predicateEndIndex)
    {
        this.predicateEndIndex = predicateEndIndex;
    }

    /**
     * Return the value of the OBJECT_TEXT column.
     * @return java.lang.String
     */
    public java.lang.String getObjectText()
    {
        return this.objectText;
    }

    /**
     * Set the value of the OBJECT_TEXT column.
     * @param objectText
     */
    public void setObjectText(java.lang.String objectText)
    {
        this.objectText = objectText;
    }

    /**
     * Return the value of the OBJECT_DIST column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getObjectDist()
    {
        return this.objectDist;
    }

    /**
     * Set the value of the OBJECT_DIST column.
     * @param objectDist
     */
    public void setObjectDist(java.lang.Integer objectDist)
    {
        this.objectDist = objectDist;
    }

    /**
     * Return the value of the OBJECT_MAXDIST column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getObjectMaxdist()
    {
        return this.objectMaxdist;
    }

    /**
     * Set the value of the OBJECT_MAXDIST column.
     * @param objectMaxdist
     */
    public void setObjectMaxdist(java.lang.Integer objectMaxdist)
    {
        this.objectMaxdist = objectMaxdist;
    }

    /**
     * Return the value of the OBJECT_START_INDEX column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getObjectStartIndex()
    {
        return this.objectStartIndex;
    }

    /**
     * Set the value of the OBJECT_START_INDEX column.
     * @param objectStartIndex
     */
    public void setObjectStartIndex(java.lang.Integer objectStartIndex)
    {
        this.objectStartIndex = objectStartIndex;
    }

    /**
     * Return the value of the OBJECT_END_INDEX column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getObjectEndIndex()
    {
        return this.objectEndIndex;
    }

    /**
     * Set the value of the OBJECT_END_INDEX column.
     * @param objectEndIndex
     */
    public void setObjectEndIndex(java.lang.Integer objectEndIndex)
    {
        this.objectEndIndex = objectEndIndex;
    }

    /**
     * Return the value of the OBJECT_SCORE column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getObjectScore()
    {
        return this.objectScore;
    }

    /**
     * Set the value of the OBJECT_SCORE column.
     * @param objectScore
     */
    public void setObjectScore(java.lang.Integer objectScore)
    {
        this.objectScore = objectScore;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof SentencePredication))
            return false;
        SentencePredication that = (SentencePredication) rhs;
        if (this.getSentencePredicationId() == null || that.getSentencePredicationId() == null)
            return false;
        return (this.getSentencePredicationId().equals(that.getSentencePredicationId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int sentencePredicationIdValue = this.getSentencePredicationId() == null ? 0 : this.getSentencePredicationId().hashCode();
            result = result * 37 + sentencePredicationIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
